# Generated by Django 2.2.7 on 2019-11-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTripDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('source', models.CharField(max_length=25)),
                ('waiting', models.CharField(max_length=35)),
                ('destination', models.CharField(max_length=30)),
                ('requestedby', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
